### ISSUE TITLE
[BUG]: Captions in audios don't work

### ISSUE THREAD

**Issue by iAkashPattnaik** [switchcollab/Switch-Bots-Python-Library#13]
**Describe the bug**
while using `app.send_audio` or `app.send_message(document=AUDIO)`, the caption parameter passed doesn't show up in app!

> [!IMPORTANT]
> I guess it's a server issue]
> Let this issue be open until it's resolved

**Comment by New-dev0** [comment]
This issue is from the application, not the server and bots library!
Closing this.
